Scope {
  uid: 1,
  block:
   Node {
     type: 'Program',
     start: 0,
     end: 81,
     loc: SourceLocation { start: [Position], end: [Position] },
     sourceType: 'module',
     interpreter: null,
     body: [ [Node], [Node], [Node] ],
     directives: [],
     leadingComments: undefined,
     innerComments: undefined,
     trailingComments: undefined },
  path:
   NodePath {
     parent:
      Node {
        type: 'File',
        start: 0,
        end: 81,
        loc: [SourceLocation],
        errors: [],
        program: [Node],
        comments: [],
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined },
     hub:
      { file: [File],
        getCode: [Function: getCode],
        getScope: [Function: getScope],
        addHelper: [Function: bound addHelper],
        buildError: [Function: bound buildCodeFrameError] },
     contexts: [ [TraversalContext] ],
     data: null,
     _traverseFlags: 0,
     state: undefined,
     opts:
      { MemberExpression: [Object],
        _exploded: {},
        _verified: {},
        BlockStatement: [Object],
        Program: [Object],
        TSModuleBlock: [Object] },
     skipKeys: null,
     parentPath: null,
     context:
      TraversalContext {
        queue: [Array],
        parentPath: undefined,
        scope: [Circular],
        state: undefined,
        opts: [Object],
        priorityQueue: [] },
     container:
      Node {
        type: 'File',
        start: 0,
        end: 81,
        loc: [SourceLocation],
        errors: [],
        program: [Node],
        comments: [],
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined },
     listKey: undefined,
     key: 'program',
     node:
      Node {
        type: 'Program',
        start: 0,
        end: 81,
        loc: [SourceLocation],
        sourceType: 'module',
        interpreter: null,
        body: [Array],
        directives: [],
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined },
     scope: [Circular],
     type: 'Program' },
  labels: Map {},
  inited: true,
  references: { hello: true, param: true, test: true },
  bindings:
   { hello:
      Binding {
        identifier: [Node],
        scope: [Circular],
        path: [NodePath],
        kind: 'const',
        constantViolations: [],
        constant: true,
        referencePaths: [Array],
        referenced: true,
        references: 1,
        hasDeoptedValue: false,
        hasValue: false,
        value: null },
     test:
      Binding {
        identifier: [Node],
        scope: [Circular],
        path: [NodePath],
        kind: 'hoisted',
        constantViolations: [],
        constant: true,
        referencePaths: [],
        referenced: false,
        references: 0,
        hasDeoptedValue: false,
        hasValue: false,
        value: null } },
  globals:
   { obj:
      Node {
        type: 'Identifier',
        start: 66,
        end: 69,
        loc: [SourceLocation],
        name: 'obj',
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined } },
  uids: {},
  data: {},
  crawling: false }